title: "MMFooty"
description: "Discover a wide variety of topics ranging from e-commerce, news, and blogs to tutorials, technology, health, travel, gaming, and finance. Stay informed, entertained, and inspired with expert advice, product reviews, and helpful resources tailored to your interests."
url: "https://www.mmfooty.com"
locale: en_US
permalink: pretty
baseurl: ""
highlighter: rouge

logo: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEin-yOkrSkvSvLX-921gqh__wUmEPM8BX5D3smW0XWiidLvAxwWP-vNclkNlh4DGyBGfpzstKFeA8r3xTRnzPVur47e-95n5FvAj3Hi4r72bOeqZspONFWQ8kUy5Tb475T1OO2aLjtNFW7EcgxZPFAVHd-YP9QJubc7ax2EwBNj9HMp0L2IJsWyuXk6jGA/s393/MMFOOTY.PNG'

markdown: kramdown

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      permalink: /:slug/
      toc: true

exclude:
  - LICENSE.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .idea
  - .jekyll-cache
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby

keep_files:
  - images

plugins:
  - jekyll-paginate-v2
  - jekyll-auto-authors
  - liquid_reading_time
  - liquid_pluralize
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-last-modified-at

pagination:
  enabled: true
  per_page: 12
  permalink: '/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true
  categories:
    enabled: true
    layouts:
      - 'list.html'
    title: 'Articles in :categories'
    silent: false
    slugify:
      mode: 'default'
      cased: true
  tags:
    enabled: true
    layouts:
      - "autopage_tags.html"
    title: "Articles taggué avec #:tag"
    permalink: "/tag/:tag"
    silent: false
    slugify:
      mode: "default"
      case: true
  authors:
    enabled: true
    data: '_data/authors.yml'
    layouts:
      - 'autopage_author.html'
    title: 'Articles par :author'
    permalink: '/author/:author/'
    slugify:
      mode: 'default'
      cased: true
  collections:
    enabled: false

feed:
  excerpt_only: true

